variables:
  PUPPETEER_VERSION: '1.18.0'
  PUPPETEER_IMAGE: $CI_REGISTRY_IMAGE/puppeteer:$PUPPETEER_VERSION
  DANGER_GITLAB_API_TOKEN: $GITLAB_TOKEN

stages:
  - pre-build
  - test
  - deploy
  - publish

.puppeteer:
  image: $PUPPETEER_IMAGE

.node:
  image: node:12
  variables:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

.yarn_install:
  before_script:
    - yarn install

build_docker_image:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.0-dind
  image: docker:stable
  stage: pre-build
  script:
    - 'mkdir -p ~/.docker'
    - >
      echo '{"experimental": "enabled"}' > ~/.docker/config.json
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./bin/build-docker.sh

danger-review:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:danger
  stage: pre-build
  dependencies: []
  only:
    variables:
      - $DANGER_GITLAB_API_TOKEN
  except:
    refs:
      - master
  script:
    - danger --fail-on-errors=true

build:
  extends: [.node, .yarn_install]
  tags:
    - gitlab-org # This allows us to use higher performance runners
  stage: test
  script:
    - yarn storybook-static
    - yarn build
    - mkdir public
    - mv storybook/* public
  artifacts:
    paths:
      - public
      - dist
      - src/scss/utilities.scss
      - scss_to_js/scss_variables.*

lint:
  extends: [.node, .yarn_install]
  stage: test
  script:
    - yarn eslint
    - yarn prettier
    - yarn stylelint
    - >
      grep -r -i '<style' --include \*.vue components
      && echo "Vue components should not contain <style tags"
      && exit 1
      || echo "No Vue component contains <style tags"

generate_utility_classes:
  extends: [.node]
  stage: test
  script:
    - yarn generate-utilities

visual:
  extends: [.puppeteer, .yarn_install]
  tags:
    - gitlab-org # This allows us to use higher performance runners
  needs:
    - build_docker_image
  stage: test
  script:
    - yarn test:visual
  artifacts:
    when: always
    paths:
      - tests/__image_snapshots__/

visual_gitlab_integration:
  extends: visual
  script:
    - yarn test:visual:gitlab
  allow_failure: true

unit_tests:
  extends: [.node, .yarn_install]
  stage: test
  script:
    - yarn test:unit

update_screenshots:
  extends: [.puppeteer, .yarn_install]
  tags:
    - gitlab-org # This allows us to use higher performance runners
  stage: pre-build
  when: manual
  script:
    - yarn test:visual:update
    - git config --global user.email "gitlab-bot@gitlab.com"
    - git config --global user.name "GitLab Bot"
    - git add .
    - "git commit -m 'chore: update snapshots'"
    - git push https://gitlab-bot:$GITLAB_TOKEN@gitlab.com/gitlab-org/gitlab-ui.git HEAD:$CI_COMMIT_REF_NAME &>/dev/null

## Secure features
include:
  - template: License-Management.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

review:
  stage: deploy
  needs:
    - build
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_COMMIT_REF_SLUG
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
    on_stop: review_stop
  only:
    - branches@gitlab-org/gitlab-ui
  except:
    - master
  tags:
    - nginx
    - review-apps
    - deploy

review_stop:
  stage: deploy
  script:
    - rm -rf public /srv/nginx/pages/$CI_COMMIT_REF_SLUG
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - branches@gitlab-org/gitlab-ui
  except:
    - master
  tags:
    - nginx
    - review-apps
    - deploy

pages:
  stage: deploy
  needs:
    - build
  script:
    - echo "Deploying to Pages"
  artifacts:
    paths:
      - public
  only:
    - master

upload_artifacts:
  extends: .node
  stage: deploy
  variables:
    TAR_ARCHIVE_NAME: gitlab-ui.$CI_COMMIT_REF_SLUG.tgz
  needs:
    - build
  script:
    - yarn pack --filename $TAR_ARCHIVE_NAME
    - echo "The package.json dependency URL is $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/$TAR_ARCHIVE_NAME"
  artifacts:
    when: always
    paths:
      - $TAR_ARCHIVE_NAME
  only:
    - /.+/@gitlab-org/gitlab-ui

publish_to_npm:
  extends: [.node, .yarn_install]
  # We need to run `publish` after pages, so that pages will get deployed
  # properly, as the publish-to-npm step will create a new commit and this
  # could lead to a side-effect where pages don't get published because of
  # the commit being made before `pages` had a chance to run
  stage: publish
  # This job doesn't use the DAG feature, because we don't want it to
  # run in case another job in the previous stages fails
  dependencies:
    - build
  script:
    - $(yarn bin)/semantic-release
  only:
    - master@gitlab-org/gitlab-ui
