image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:gitlab-puppeteer"

stages:
    - test
    - build
    - deploy
    - release

build:
  stage: build
  script:
    - yarn install
    - yarn storybook-static
    - mkdir public
    - mv storybook/* public
    - npm unpublish @gitlab-org/gitlab-ui@1.8.0-ie11
  artifacts:
    paths:
      - public
